### PR TITLE
Jesse/suggested users

### PR DESCRIPTION
**Pull request by ChenJesse**
EDIT: Figured some workarounds, everything seems to be working pretty well.

If you click the "FOLLOW" button, you are now following the user, if you click it again, you will unfollow. If you click anywhere else in the cell, it brings you to their profile. If you scroll down to the bottom, it will load another page of suggestions for you.

### CODE REVIEW

**Comment by say25** [comment]
Suggestions does not appear in side bar on iPhone 5 screen size or smaller
screen shot 2015-12-08 at 2 44 31 am

**Comment by lucasderraugh** [comment]
I've got the fix for it.

**Comment by lucasderraugh** [comment]
@ChenJesse This branch is ok to be merged in. Please rebase off master and merge.

**Comment by lucasderraugh** [comment]
Rebased and merged

**Pull request closed without merging**
