### PR TITLE
Swipe left to close sidebar

### PR DESCRIPTION
**Pull request by ChenJesse**

### CODE REVIEW

**Review by loganallen — APPROVED** [review]
Nice

**Comment by anniexcheng** [comment]
@ChenJesse when you click on a cell while in the sidebar view, does the song start playing?

**Comment by ChenJesse** [comment]
@acheng96 Yea it does, is that not preferred?

**Comment by anniexcheng** [comment]
@ChenJesse yea I believe that's the reason we set userEnabled to false. But this is a design decision you guys should talk about

**Comment by ChenJesse** [comment]
I think we should implement this change right now. 
I just realized that the main problem is that if you happen to swipe on a cell that is playing, it will scrub the song backwards, but we are planning to redesign the feed to having a constant sticky cell that shows the song being played (like Spotify), so when we make that change, we can disable view interaction in that sticky cell.

Making that constant sticky cell should solve a lot of the UI/UX issues on the backlog.

Actually nevermind, there are some other problems with this fix. I guess we can just deal with this later.

**Pull request closed without merging**
