### PR TITLE
Fix syncing issues between add buttons on LikedTableVC and playerCells

### PR DESCRIPTION
**Pull request by ChenJesse**

### CODE REVIEW

**Comment by say25** [comment]
Wouldn't this be a great opportunity to move to using the ParentPlayerCellView.swift to handle this?

**Comment by ChenJesse** [comment]
You're right, but at this point I want to avoid messing with the codebase as much as possible so that we can stabilize for the MVP, I would prefer to tackle the transition next semester tbh

**Comment by say25** [comment]
While I agree the cleaner the code base the easier it will be to patch bugs. As that is a "major" change I see and understand the justification for waiting for a significant version bump. I might personally have time to investigate this in the next few days.

**Comment by ChenJesse** [comment]
Ok, I refactored it out, its actually a lot cleaner now, good suggestion

**Comment by loganallen** [comment]
Looks good to me

**Pull request merged**
