### PR TITLE
Natasha/UIupdates

### PR DESCRIPTION
**Pull request by natashaarmbrust**
TEMPO

### CODE REVIEW

**Comment by lucasderraugh** [comment]
@natashaarmbrust Was the record supposed to continuously rotate?

**Comment by say25** [comment]
I believe we decided against it for now as we don't have large images from design. @natashaarmbrust or @dennisfedorko should know more.

**Comment by natashaarmbrust** [comment]
Yup steven is right. We decided to wait for final designs

**Comment by lucasderraugh** [comment]
Got ya, I'll look the rest over and merge it in tonight. Looks pretty gucci.

**Comment by anniexcheng** [comment]
Merged with 9704685

**Pull request closed without merging**
