### PR TITLE
Daniel/peekandpop

### PR DESCRIPTION
**Pull request by dantheli**
Implements peek and pop in the following places:
- To profile from profile image on Feed
- To Followers/Following screen on profile screen
- To Post History screen on profile screen
- To profile on People Search

Did not implement large profile image since Monica's branch is adding that behavior

### CODE REVIEW

**Comment by lucasderraugh** [comment]
Remind me to see this implementation while in meeting tonight. It's hard to evaluate all the code without seeing what is actually does ;)

**Comment by lucasderraugh** [comment]
Could we move these outside the main class and add them to an extension:

``` swift
@available(iOS 9.0, *)
extension FeedViewController: UIViewControllerPreviewingDelegate { ... methods ... }
```

Makes for a cleaner view of what's the more important stuff to the class.

**Comment by dantheli** [comment]
Should a create a new Swift file and put extensions for every VC that implements the PreviewingDelegate? Or is there a good place for them already?

**Comment by lucasderraugh** [comment]
I would keep them in the same file, but it's nice to have extensions separate from the main code.

**Comment by lucasderraugh** [comment]
@dantheli Looks good, sorry forgot to comment on this yesterday.

**Pull request merged**
