### PR TITLE
Jesse/rename project

### PR DESCRIPTION
**Pull request by ChenJesse**
Should be most of the work with renaming the project. I didn't touch the info.plist file, which has some mentions of icefishing, wasn't sure if it would break anything. The properties are: 
FacebookDisplayName = Icefishing, 
URL types -> Item 1 -> URL identifier = com.cuappdev.IceFishing.spotify-auth, 
URL types -> Item 1 -> URL schemes -> Item 0 -> icefishing-login.

Any other mention of icefishing are just endpoint names for the backend. 

The SDK for Spotify was also updated (by around 30 commits), but I played around w/ the app and everything seemed to work fine.

Steps taken:
    1.  Change your product name (https://developer.apple.com/library/ios/recipes/xcode_help-project_editor/RenamingaProject/RenamingaProject.html)
    2.  Close the project in Xcode
    3.  Discard the existing .xcworkspace, Pods folder & Podfile.lock
    4.  Change Podfile target from icefishing to Tempo (maybe have to change Tempo Build Settings to None)
    5.  Run pod install again.
    6.  Change Build Phases, renaming anything with icefishing to Tempo
    7.  Manually rename all the comments
    8.  Change the physical directory name following these instructions (http://stackoverflow.com/questions/8262613/renaming-xcode-4-project-and-the-actual-folder)
    9.  Modify the ios-sdk submodule by changing path (in .gitmodules)

### CODE REVIEW

**Comment by anniexcheng** [comment]
Looks good! We need to change some app settings in the Facebook Developer Portal before we make changes to the Info.plist properties but that can be done in another issue. You're good to check this in once @loganallen signs off as well.

**Comment by loganallen** [comment]
Seems fine to me!

**Comment by anniexcheng** [comment]
Addresses #33

**Comment by anniexcheng** [comment]
Merged with f216958

**Pull request merged**
